Add GDI
neoforged/GradleUtils pull request #14
Opened 2023-12-02 15:59 UTC by Matyrobbrt

Adds GDI for dsl property helpers.

2023-12-02 16:59 UTC, marchermans requested changes

2023-12-02 16:59 UTC, marchermans commented on build.gradle
> +    final gdiVersion = '1.0.13'
Move this into a Gradle properties file

2023-12-02 21:12 UTC, marchermans approved these changes

2023-12-12 11:50 UTC, Matyrobbrt commented
test

2023-12-12 11:51 UTC, merged